//
//  DIContainer+AutoDI.swift
//  DiContainer
//
//  Created by Wonji Suh on 2024.
//

import Foundation

// MARK: - Auto DI Features

/// 자동 의존성 주입 기능 확장
public extension DIContainer {

  /// 🚀 자동 생성된 의존성 그래프를 시각화합니다
  ///
  /// 별도 설정 없이 자동으로 수집된 의존성 관계를 텍스트로 출력합니다.
  func getAutoGeneratedGraph() -> String {
    AutoDIOptimizer.readSnapshot().graphText
  }

  /// ⚡ 자동 최적화된 타입들을 반환합니다
  ///
  /// 사용 패턴을 분석하여 자동으로 성능 최적화가 적용된 타입들의 목록입니다.
  func getOptimizedTypes() -> Set<String> {
    let freq = AutoDIOptimizer.readSnapshot().frequentlyUsed
    return Set(freq.filter { $0.value >= 3 }.keys)
  }

  /// ⚠️ 자동 감지된 순환 의존성을 반환합니다
  ///
  /// 의존성 등록/해결 과정에서 자동으로 감지된 순환 의존성 목록입니다.
  func getDetectedCircularDependencies() -> Set<String> {
    let snap = AutoDIOptimizer.readSnapshot()
    var visited: Set<String> = []
    var stack: Set<String> = []
    var cycles: Set<String> = []
    func dfs(_ node: String) {
      if stack.contains(node) { cycles.insert("순환 감지: \(node)"); return }
      if visited.contains(node) { return }
      visited.insert(node); stack.insert(node)
      for dep in snap.dependencies where dep.from == node { dfs(dep.to) }
      stack.remove(node)
    }
    for t in snap.registered where !visited.contains(t) { dfs(t) }
    return cycles
  }

  /// 📊 자동 수집된 성능 통계를 반환합니다
  ///
  /// 각 타입의 사용 빈도가 자동으로 추적됩니다.
  func getUsageStatistics() -> [String: Int] {
    AutoDIOptimizer.readSnapshot().frequentlyUsed
  }

  /// 🔍 특정 타입이 자동 최적화되었는지 확인합니다
  ///
  /// - Parameter type: 확인할 타입
  /// - Returns: 최적화 여부
  func isAutoOptimized<T>(_ type: T.Type) -> Bool {
    let name = String(describing: type)
    let freq = AutoDIOptimizer.readSnapshot().frequentlyUsed
    return (freq[name] ?? 0) >= 5
  }

  /// ⚙️ 자동 최적화 기능을 제어합니다
  ///
  /// - Parameter enabled: 활성화 여부 (기본값: true)
  func setAutoOptimization(_ enabled: Bool) {
    Task { @DIActor in AutoDIOptimizer.shared.setOptimizationEnabled(enabled) }
  }

  /// 🧹 자동 수집된 통계를 초기화합니다
  func resetAutoStats() {
    Task { @DIActor in AutoDIOptimizer.shared.resetStats() }
  }
}
