import WeaveDI
import Foundation

// 중급 04-02: 운영/모니터링 + 성능 최적화 사용 예

func exampleOpsAndMonitoring() async {
    // 1) 최적화 설정 및 활성화
    UnifiedDI.configureOptimization(debounceMs: 100, threshold: 10, realTimeUpdate: true)
    UnifiedDI.enableOptimization(true)

    // 2) 몇 가지 샘플 등록/해석으로 통계 생성
    _ = UnifiedDI.register(String.self) { "demo" }
    _ = UnifiedDI.resolve(String.self)

    // 3) 통계/그래프/제안 수집
    let stats = DIContainer.live.getUsageStatistics()      // 사용 빈도
    let top = UnifiedDI.getTopUsedTypes()                  // TOP 사용 타입
    let tips = UnifiedDI.getOptimizationTips()             // 최적화 제안
    let graph = DIContainer.live.getAutoGeneratedGraph()   // 자동 그래프 (텍스트)

    // 4) 출력/활용 (여기서는 단순 참조)
    _ = (stats, top, tips, graph)
}

